First checkin for M365 Services Health SPFx webpart
pnp/sp-dev-fx-webparts pull request #3476
Opened 2023-02-14 19:06 UTC by HarminderSethi

> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

> To submit a pull request with multiple authors, make sure that at least one commit is a co-authored commit by adding a `Co-authored-by:` trailer to the commit's message. E.g.: `Co-authored-by: name <name@example.com>`

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                             |
| New sample?     | yes                               |
| Related issues? | N/A |

## What's in this Pull Request?
1. Show the health status for all the M365 services
2. Complete details including all the updates for all the impacted services

2023-02-18 21:13 UTC, hugoabernier requested changes
@HarminderSethi this sample looks great, please make the changes listed in this review so we can merge the PR.

2023-02-18 21:13 UTC, hugoabernier commented on samples/react-m365-services-health/README.md
> +> Any special pre-requisites?
Please update the README.md to provide the required steps to allow permissions for the sample.

2023-02-18 21:13 UTC, hugoabernier commented on samples/react-m365-services-health/src/common/services/GraphService.ts
> +	public getHealthOverviews = async (): Promise<any> => {
Is there any way not to use `any` here?

2023-02-18 21:13 UTC, hugoabernier commented on samples/react-m365-services-health/src/common/services/HelperService.ts
> +export namespace HelperService {
Consider https://typescript-eslint.io/rules/no-namespace/

2023-02-18 21:13 UTC, hugoabernier commented on samples/react-m365-services-health/src/common/services/HelperService.ts
> +			case "microsoft mefender for cloud apps":
Should this be `defender`?

2023-02-18 21:13 UTC, hugoabernier commented on samples/react-m365-services-health/src/webparts/m365ServicesHealth/services/ListViewHelperService.ts
> +export namespace ListViewHelperService {
Consider https://typescript-eslint.io/rules/no-namespace/

2023-02-18 21:13 UTC, hugoabernier commented on samples/react-m365-services-health/README.md
> +# Microsoft 365 Services Health
Try renaming it "Service Health for Microsoft 365" to comply with Microsoft branding guidelines.

2023-02-20 17:40 UTC, hugoabernier approved these changes

2023-02-20 17:40 UTC, merged

2023-02-20 17:49 UTC, HarminderSethi commented
Thanks @hugoabernier 😊

2023-02-20 18:12 UTC, hugoabernier commented
Thank you @HarminderSethi for this sample. Would you be interested in demoing on the April 20th SPFx community call? You'd have 10-13 minutes to demo your web part and review code highlights.

2023-02-21 01:27 UTC, HarminderSethi commented
@hugoabernier Yes, I would be interested in demoing in SPFx community call. Thank you for the opportunity to showcase my web part.

2023-02-21 05:30 UTC, hugoabernier commented
Perfect! I have you confirmed for April 20th. Can't wait to see your demo!