Dev
pnp/sp-dev-fx-webparts pull request #3652
Opened 2023-04-09 13:01 UTC by jtlivio

# SAMPLE

**react-timeline-3rdparty**

## SPFx 1.17.0

|        Q        |                    A                    |
| --------------- | --------------------------------------- |

| New sample?     | yes                              |

## What's in this Pull Request?

This web part is a sample in how you can create a Beautiful TIMELINE with dynamic values from a SharePoint List
This sample show how it's possible to use other controls provided in the GitHub and implement in the SPFx. 

- [Uses react-vertical-timeline-component](https://github.com/stephane-monnot/react-vertical-timeline) [MIT Licence](https://mit-license.org/)
- [Uses PnPJs V3](https://pnp.github.io/pnpjs/getting-started/)
- In this sample I'm not using Caching from the PnPJs V3, feel free to change

2023-04-14 13:55 UTC, hugoabernier requested changes
Can you please change your PR to only affect the react-timeline-3rdparty folder. It should not touch any other folders.

2023-04-14 17:21 UTC, jtlivio commented
@hugoabernier sure, thank you

2023-04-14 17:31 UTC, hugoabernier requested changes

2023-04-18 06:56 UTC, jtlivio commented on samples/react-timeline-3rdparty/src/webparts/myTimeline/components/MyTimeline.tsx
> +          <div className={styles.welcome}>
@hugoabernier thank you

2023-04-18 06:57 UTC, jtlivio commented on samples/react-timeline-3rdparty/src/webparts/myTimeline/components/MyTimeline.tsx
> +                  iconStyle={{ background: 'rgb(16, 204, 82)', color: '#fff' }}
@hugoabernier thank you

2023-04-18 06:57 UTC, jtlivio commented on samples/react-timeline-3rdparty/src/webparts/myTimeline/components/MyTimeline.tsx
> +                      className="vertical-timeline-element--work"
@hugoabernier thank you

2023-04-18 06:58 UTC, jtlivio commented on samples/react-timeline-3rdparty/src/webparts/myTimeline/components/MyTimeline.tsx
> +  background: 'rgb(227, 227, 227)'
@hugoabernier thank you

2023-04-20 16:59 UTC, closed without merging