updated to 1.20.0
pnp/sp-dev-fx-webparts pull request #5277
Opened 2024-10-02 18:02 UTC by ValerasNarbutas

> By submitting this pull request, you agree to the [contribution guidelines](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

> To submit a pull request with multiple authors, make sure that at least one commit is a co-authored commit by adding a `Co-authored-by:` trailer to the commit's message. E.g.: `Co-authored-by: name <name@example.com>`

> Put an `x` in all the items that apply (`[x]`, no spaces between the `[`, the `x`, and the `]` ), make notes next to any that haven't been addressed.

- [ ] New sample
- [x] Bug fix/update
- [x] Related issues: #5252

## What's in this Pull Request?

SPFX upgrade to 1.20.0 version

## Node Version
Node version used: 18.17.1

## Checklist

- [x] My pull request affects only ONE sample.
- [x] My sample builds without any warnings
- [x] I have updated the `README.md` file's **Version history**. For new samples, created a new `README.md` file matching [this template](templates/README-template.md)
- [x] My `README.md` has at least one static high-resolution screenshot (i.e. not a GIF) located in the `assets` folder.
- [x] My `README.md` contains complete setup instructions, including pre-requisites and permissions required
- [x] My solution includes a `.nvmrc` file indicating the version of Node.js

2024-10-05 21:05 UTC, Adam-it commented
Thank you for opening a PR to our samples repo and helping us upgrade our project 👍
We will try to review this PR ASAP

2024-10-11 19:38 UTC, Adam-it requested changes
@ValerasNarbutas Awesome work 👏👏👏 You Rock 🤩
I managed to build it locally and played with it a bit.
During my review I noticed some small details we could sort out before we merge 👍. Please do give them a double check 🙏

2024-10-11 19:38 UTC, Adam-it commented on samples/react-birthdays/src/assets/sample.json
I think this file should not be here. The `sample.json` should be present in the `assets` folder in the root of the project and is used to store metadata for sample galleries. We should remove this instance here and leave only the one we already have in the `react-birthday/assets`
Along the way there we should update the `SPFX-VERSION` to 1.20.0

2024-10-11 19:38 UTC, Adam-it commented on samples/react-birthdays/package.json
> +  "name": "happy-birthday",
why change the name?

2024-10-11 19:38 UTC, Adam-it commented on samples/react-birthdays/package.json
> +  "version": "0.0.1",
we should  either not change the version number to make it higher but not smaller

2024-10-12 16:51 UTC, hugoabernier commented
@ValerasNarbutas do you mind taking a look at the code or instructions. The build seems to produce the following error in certain cases:
{
    "statusCode": 400,
    "code": "invalidRequest",
    "requestId": "3dbfa519-574b-41b2-b9e2-42b605801c77",
    "date": "2024-10-12T20:43:53.000Z",
    "body": "{\"code\":\"invalidRequest\",\"message\":\"Field 'Birthday' cannot be referenced in filter or orderby as it is not indexed. Provide the 'Prefer: HonorNonIndexedQueriesWarningMayFailRandomly' header to allow this, but be warned that such queries may fail on large lists.\",\"innerError\":{\"date\":\"2024-10-12T16:43:53\",\"request-id\":\"3dbfa519-574b-41b2-b9e2-42b605801c77\",\"client-request-id\":\"429059bb-c957-5969-ae5a-84515e5d9870\"}}"
}

2024-10-12 17:27 UTC, ValerasNarbutas commented
> @ValerasNarbutas do you mind taking a look at the code or instructions. The build seems to produce the following error in certain cases:
> {
>     "statusCode": 400,
>     "code": "invalidRequest",
>     "requestId": "3dbfa519-574b-41b2-b9e2-42b605801c77",
>     "date": "2024-10-12T20:43:53.000Z",
>     "body": "{\"code\":\"invalidRequest\",\"message\":\"Field 'Birthday' cannot be referenced in filter or orderby as it is not indexed. Provide the 'Prefer: HonorNonIndexedQueriesWarningMayFailRandomly' header to allow this, but be warned that such queries may fail on large lists.\",\"innerError\":{\"date\":\"2024-10-12T16:43:53\",\"request-id\":\"3dbfa519-574b-41b2-b9e2-42b605801c77\",\"client-request-id\":\"429059bb-c957-5969-ae5a-84515e5d9870\"}}"
> }

Will do @hugoabernier

2024-10-12 18:10 UTC, ValerasNarbutas commented
thanks for checking  @Adam-it  and @hugoabernier , will review this.

2024-10-13 12:03 UTC, ValerasNarbutas commented
> Birthday

Hey @hugoabernier , did you indexed "Birthday", it is in instructions
![image](https://github.com/user-attachments/assets/bfdd2b0d-f661-4e4f-bdd9-5ac4d9b574d2)

2024-10-21 03:56 UTC, merged

2024-10-21 03:56 UTC, hugoabernier commented
Many thanks @ValerasNarbutas for your update! Awesome!.

Thank you for sharing your sample with others - you rock! 👏🥇👩‍💻