Upgraded react-datatable SPFx to version 1.20.0
pnp/sp-dev-fx-webparts pull request #5312
Opened 2024-10-21 08:01 UTC by mohammadamer

- [ ] New sample
- [x] Bug fix/update
- [ ] Related issues: fixes #X, partially #Y, mentioned in #Z

## What's in this Pull Request?
Upgraded react-datatable SPFx to version 1.20.0
Fixed a bug when exporting to PDF

## Node Version
20.16.0

Node version used:
20.16.0

## Checklist

- [x] My pull request affects only ONE sample.
- [ ] My sample builds without any warnings
- [x] I have updated the `README.md` file's **Version history**. For new samples, created a new `README.md` file matching [this template](templates/README-template.md)
- [x] My `README.md` has at least one static high-resolution screenshot (i.e. not a GIF) located in the `assets` folder.
- [x] My `README.md` contains complete setup instructions, including pre-requisites and permissions required
- [x] My solution includes a `.nvmrc` file indicating the version of Node.js

2024-10-22 20:26 UTC, Adam-it requested changes
@mohammadamer awesome work 👏👏👏👏 
I managed to build the solution and play with it. 
I noticed some tiny details we could sort out before we merge. Please do give them a double check 🙏

2024-10-23 08:16 UTC, mohammadamer commented on samples/react-datatable/.nvmrc
> +20.16.0
Well, As per the upgrade file generated by the SPFx toolkit, I did use version 20.16.0
But if it works with 18 then I can also change it. What exactly 18 version to replace?

`{
  "@microsoft/generator-sharepoint": {
    "nodeVersion": "20.16.0"
  }
}`

2024-10-23 08:16 UTC, mohammadamer commented on samples/react-datatable/.yo-rc.json
> +        "nodeVersion": "20.16.0"
Then Please tell me what exactly the 18 node version to include.

2024-10-23 08:23 UTC, mohammadamer commented on samples/react-datatable/README.md
I would suggest to add check in the PR templates for these 2 updates
1. assets/sample.json
2. devcontainer.json

2024-10-23 16:49 UTC, mohammadamer commented
@Adam-it 
All comments are resolved :)

2024-10-24 22:56 UTC, Adam-it commented on samples/react-datatable/.yo-rc.json
> +        "nodeVersion": "20.16.0"
SPFx 1.20 works with any version of Node v18 as we may find in the MS docs
![image](https://github.com/user-attachments/assets/129b969c-5a4c-4c8e-86f4-68a4d367ef73)

2024-10-24 22:58 UTC, Adam-it commented on samples/react-datatable/.nvmrc
> +20.16.0
Sorry for the late reply 🙏
We may use any version of Node v18 for SPFx 1.20 from what I am aware so I would go w latest.
as for the snippet you provided. May I kindly ask you about a bit more context. When running which action/command you get this result? is it part of some bigger output?

2024-10-24 22:59 UTC, Adam-it commented on samples/react-datatable/README.md
@mohammadamer this is a good suggestion indeed. I will tag @hugoabernier as he is the maintainer of this repo to check this suggestion. I may only add that sample updates are maybe not something done on regular bases so I am not entirely sure this should be part of PR template 🤔

2024-10-24 23:29 UTC, Adam-it approved these changes
Looks great now 👏👏👏

2024-10-24 23:33 UTC, merged