React graph app secret expiration upgrade to SPFx v1.20
pnp/sp-dev-fx-webparts pull request #5357
Opened 2024-12-09 21:32 UTC by a1mery

- [ ] New sample
- [x] Bug fix/update
- [ ] Related issues: fixes #X, partially #Y, mentioned in #Z

## What's in this Pull Request?

Upgrade sample to SPFx version 1.20

## Node Version

Node version used: v18.18.0

## Checklist

- [x] My pull request affects only ONE sample.
- [x] My sample builds without any warnings
- [x] I have updated the `README.md` file's **Version history**. For new samples, created a new `README.md` file matching [this template](templates/README-template.md)
- [x] My `README.md` has at least one static high-resolution screenshot (i.e. not a GIF) located in the `assets` folder.
- [x] My `README.md` contains complete setup instructions, including pre-requisites and permissions required
- [x] My solution includes a `.nvmrc` file indicating the version of Node.js

2025-01-08 23:56 UTC, Adam-it requested changes
@a1mery Awesome work 👏. You Rock 🤩

I added a few comments regarding dependencies we should fixup before we merge.
We should also update the `assets/sample.json`. This is metadata file that is used to present sample in the gallery. There you will find `SPFX-VERSION` which should be updated to `1.20.0`

2025-01-08 23:56 UTC, Adam-it commented on samples/react-graph-app-secret-expiration/package.json
> +    "@microsoft/eslint-plugin-spfx": "1.18.2",
We should align this to `1.20.0`

```suggestion
    "@microsoft/eslint-config-spfx": "1.20.0",
    "@microsoft/eslint-plugin-spfx": "1.20.0",
```

2025-01-08 23:56 UTC, Adam-it commented on samples/react-graph-app-secret-expiration/package.json
> +    "@microsoft/rush-stack-compiler-4.7": "0.1.0",
it seems we have rush stack compiler twice now. the first one which is 4.5 should be removed

2025-01-08 23:56 UTC, Adam-it commented on samples/react-graph-app-secret-expiration/package.json
> +    "@microsoft/sp-module-interfaces": "1.18.2",
if I am not mistaken this should also be `1.20.0`

```suggestion
    "@microsoft/sp-build-web": "1.20.0",
    "@microsoft/sp-module-interfaces": "1.20.0",
```

2025-01-09 07:53 UTC, a1mery commented
@Adam-it thanks a lot for the review!! ☺️ I will take care of it 💪

2025-01-10 13:33 UTC, a1mery commented on samples/react-graph-app-secret-expiration/package.json
> +    "@microsoft/sp-module-interfaces": "1.18.2",
Hi @Adam-it ,

For the following packages:
- @microsoft/eslint-config-spfx
- @microsoft/eslint-plugin-spfx
- @microsoft/sp-build-web
- @microsoft/sp-module-interfaces

I would suggest to keep version 1.18.2.

I'm upgrading this sample from version **1.16.1** and cmdlet `m365 spfx project upgrade` indicated to upgrade those packages to **1.18.2**.
I still tried to upgrade those package to 1.20.0 and `npm install` was failing saying the version does not exist.
`npm install` worked fine with version 1.20.2 (for those 4 packages listed above), but i caused errors when building the web part.

What is your opinion on this?

2025-01-10 14:12 UTC, a1mery commented
@Adam-it I was able to make suggested changes!
Upgrading `eslint` packages was a bit more complex than expected but I made it 😊

2025-01-12 15:45 UTC, Adam-it commented
> @Adam-it I was able to make suggested changes! Upgrading `eslint` packages was a bit more complex than expected but I made it 😊

Thank you for your awesome work and ASAP response 👍. You are awesome 🤩
I will do my very best to find time for this PR in the upcoming week.

2025-01-13 17:35 UTC, merged

2025-01-13 17:35 UTC, hugoabernier commented
Thank you @a1mery for your update! Awesome!.

Thank you for sharing your sample with others - you rock! 👏🥇👩‍💻